apiVersion: v1
kind: Secret
metadata:
  name: updateer-secrets
type: Opaque
stringData:
  # Replace these with your actual values (no need to base64 encode here, kubectl handles it)
  RESEND_API_KEY: "re_ZWPceXdW_Giq8HhdHgSwL9zuHZYZscj3x" # FROM YOUR .ENV
  RESEND_WEBHOOK_SECRET: "whsec_qcMVT6ZJcHLbEIApTdX+D3p/vdVcTNLV" # FROM YOUR .ENV
  TUNNEL_TOKEN: "eyJhIjoiMTQ1OTJkZGMzZTFkOWVkYmIyMmRjNTgzYjk5YTMzNGMiLCJ0IjoiNjJmMTdlMjgtMjg4Yi00OGE4LTljYjYtMmZhMmI5YmQ5NWI2IiwicyI6Ik16RXpNell6WXpVdFpqWmlOUzAwWW1FMkxXSTBOVFV0T0RCbE9XRXhZMkU1TVRFNCJ9" # FROM YOUR .ENV
  
  # Backend Secrets (From docker-compose.yml)
  DB_URL: "host=mail-db user=admin password=secretpassword dbname=mail_manager port=5432 sslmode=disable" # UPDATE HOST/PASSWORD FOR PROD
  JWT_SECRET: "replace-this-with-a-secure-random-string-in-prod"
  ADMIN_SECRET_KEY: "qwertyuiop" # CHANGE THIS IN PROD
  MINIO_ROOT_PASSWORD: "password123" # CHANGE THIS IN PROD
